import { Topic } from '../types';

export const listsStringsTopic: Topic = {
  id: '05_lists_strings',
  title: 'Lists, Strings & Comprehensions',
  scope: 'final',
  description: 'Master list slicing, string index steps, list comprehensions, immutability, and nested list mutations.',
  iconName: 'ListFilter',
  questions: [
    {
      id: 'list_01',
      topicId: '05_lists_strings',
      topicTitle: 'Lists, Strings & Comprehensions',
      scope: 'final',
      title: 'List Comprehension with String Multiplication',
      type: 'mcq',
      difficulty: 'medium',
      description: 'What is the output of the following code snippet?',
      codeSnippet: `x = [i * 2 for i in '123']
print(x)`,
      options: [
        { id: 'A', text: "['246']", isCodeFont: true },
        { id: 'B', text: "['2', '4', '6']", isCodeFont: true },
        { id: 'C', text: "['11', '22', '33']", isCodeFont: true },
        { id: 'D', text: "['123123']", isCodeFont: true },
        { id: 'E', text: 'TypeError: cannot multiply string by int', isCodeFont: false }
      ],
      correctOptionId: 'C',
      explanation: "Iterating `'123'` yields characters `'1'`, `'2'`, `'3'`. Multiplying a string by 2 duplicates it: `'1' * 2 = '11'`, `'2' * 2 = '22'`, `'3' * 2 = '33'`. So `x = ['11', '22', '33']`."
    },
    {
      id: 'list_02',
      topicId: '05_lists_strings',
      topicTitle: 'Lists, Strings & Comprehensions',
      scope: 'final',
      title: 'String Extended Slicing Step',
      type: 'tracing',
      difficulty: 'medium',
      description: 'Trace the output string `str3` generated by negative step slicing `str2[::-2]`.',
      codeSnippet: `1: str1 = 'Jennie'
2: str2 = 'Solooooo'
*3: str3 = str1 + str2[::-2]`,
      variablesToTrack: ['str1', 'str2', 'str3'],
      targets: [
        { line: 3, vars: ['str1', 'str2', 'str3'] }
      ],
      answers: {
        '3-str1': "'Jennie'",
        '3-str2': "'Solooooo'",
        '3-str3': "'JennieoolS'"
      },
      explanation: "`str2` is `'Solooooo'` (length 8). `str2[::-2]` starts from end (index 7: `'o'`), stepping backward by 2: index 7 `'o'`, index 5 `'o'`, index 3 `'l'`, index 1 `'S'`, producing `'oolS'`. Concatenating with `'Jennie'` yields `'JennieoolS'`."
    },
    {
      id: 'list_03',
      topicId: '05_lists_strings',
      topicTitle: 'Lists, Strings & Comprehensions',
      scope: 'final',
      title: 'Equivalent List Comprehension Syntax',
      type: 'mcq',
      difficulty: 'hard',
      description: 'Which list comprehension is functionally equivalent to the imperative loop below?',
      codeSnippet: `output = []
for x in range(10, 0, -1):
    if x % 2 != 0:
        output.append(x * x)`,
      options: [
        { id: 'A', text: 'output = [x*x for x in range(10, 0, -1) if x%2 != 0]', isCodeFont: true },
        { id: 'B', text: 'output = [x*x for x in range(10) if x%2 != 0]', isCodeFont: true },
        { id: 'C', text: 'output = [output.append(x*x) for x in range(10) if x%2 != 0]', isCodeFont: true },
        { id: 'D', text: 'output = [for x in range(10,0,-1) if x%2 != 0 x*x]', isCodeFont: true },
        { id: 'E', text: 'None of the above', isCodeFont: false }
      ],
      correctOptionId: 'A',
      explanation: 'List comprehension syntax format is `[expression for item in iterable if condition]`. Option A preserves the exact reverse range `range(10, 0, -1)`, odd check `if x%2 != 0`, and expression `x*x`.'
    },
    {
      id: 'list_04',
      topicId: '05_lists_strings',
      topicTitle: 'Lists, Strings & Comprehensions',
      scope: 'final',
      title: 'Nested List Mutation vs Tuple Inside List',
      type: 'mcq',
      difficulty: 'hard',
      description: 'What happens when executing the following code?',
      codeSnippet: `cars = [('Mini Cooper', 'F56'), ('Audi', 'e-tron GT')]
if len(cars) == 2:
    cars[0] = ('BMW', 'Z4')
else:
    cars[1][1] = 'A1'
print(cars)`,
      options: [
        { id: 'A', text: "[('Mini Cooper', 'F56'), ('Audi', 'e-tron GT')]", isCodeFont: true },
        { id: 'B', text: "[('BMW', 'Z4'), ('Audi', 'e-tron GT')]", isCodeFont: true },
        { id: 'C', text: "[('BMW', 'Z4'), ('Mini Cooper', 'F56'), ('Audi', 'e-tron GT')]", isCodeFont: true },
        { id: 'D', text: "TypeError: 'tuple' object does not support item assignment", isCodeFont: false },
        { id: 'E', text: 'None of the above', isCodeFont: false }
      ],
      correctOptionId: 'B',
      explanation: '`len(cars)` is 2 (`True`). The `if` branch executes `cars[0] = ("BMW", "Z4")`. Replaces element 0 of list `cars` (lists are mutable!). The `else` branch (which would try to mutate a tuple and fail) is NOT executed. Result: `[("BMW", "Z4"), ("Audi", "e-tron GT")]`.'
    },
    {
      id: 'list_05',
      topicId: '05_lists_strings',
      topicTitle: 'Lists, Strings & Comprehensions',
      scope: 'final',
      title: 'Filtering List Comprehension Completion',
      type: 'completion',
      difficulty: 'medium',
      description: 'Complete the list comprehension in blank [1] to filter names that start with letter `"A"`.',
      codeSnippet: `names = ['Apiwat', 'Athirat', 'Benjapon', 'Chanapa', 'Danai']
a_names = [i for i in names if ___1___]`,
      blanks: [
        { id: '1', label: 'Blank [1] (Condition for starting with "A")', placeholder: 'Type the condition here', hint: 'How do you access the first character of string i and compare it?' }
      ],
      answers: {
        '1': "i[0] == 'A'"
      },
      explanation: '`i[0]` accesses the first character of each string element. `i[0] == "A"` checks if the name starts with letter `"A"`.'
    },
    {
      id: 'list_06',
      topicId: '05_lists_strings',
      topicTitle: 'Lists, Strings & Comprehensions',
      scope: 'final',
      title: '2D Matrix Grid List Generation',
      type: 'tracing',
      difficulty: 'hard',
      description: 'Trace variable `square` at line 7 generated by nested loops.',
      codeSnippet: `1: square = []
2: for i in range(2):
3:     inner = []
4:     for j in range(2):
5:         inner.append(i + j)
6:     square.append(inner)
*7: print(square)`,
      variablesToTrack: ['square'],
      targets: [
        { line: 7, vars: ['square'] }
      ],
      answers: {
        '7-square': '[[0, 1], [1, 2]]'
      },
      explanation: '`i=0`: `inner` gets `0+0=0, 0+1=1` -> `[0, 1]`.\n`i=1`: `inner` gets `1+0=1, 1+1=2` -> `[1, 2]`.\n`square` becomes `[[0, 1], [1, 2]]`.'
    }
  ]
};
